title: TERRA ODD
permalink: pretty
remote_theme: pmarsceill/just-the-docs
site.url: https://cairnrpg.com
# logo: "/img/logo.png"
color_scheme: light
encoding: UTF-8
plugins:
  - jekyll-redirect-from
include:
  - js

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# footer_content: "The text on this page is licensed under <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">CC-BY-SA 4.0.</a>"
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# If you want to ignore the monsters folder during builds
# exclude: /resources/monsters

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.1"

